---
run:
  concurrency: 6
  timeout: 5m
issues:
  # Maximum issues count per one linter.
  # Set to 0 to disable.
  # Default: 50
  max-issues-per-linter: 0
  # Maximum count of issues with the same text.
  # Set to 0 to disable.
  # Default: 3
  max-same-issues: 0
  new-from-rev: ""
  exclude-rules:
    - path: '(.+)_test\.go'
      linters:
        - err113
        - funlen
        - goconst
        - gocyclo
        - lll
        - wrapcheck
  # probes must register via init
    - path: 'probes/.+/impl.go'
      linters:
        - gochecknoinits
linters:
  enable:
    - asciicheck
    - copyloopvar
    - dogsled
    - err113
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - forbidigo
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - gofumpt
    - goheader
    - goimports
    # manage use of replace, retract and exclude directives (see https://github.com/ossf/scorecard/pull/3440#issuecomment-1708904830)
    # https://golangci-lint.run/usage/linters/#gomoddirectives
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - mirror
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - predeclared
    - staticcheck
    - stylecheck
    - thelper
    - typecheck
    - unconvert
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
    - wrapcheck
  disable:
    - exhaustruct # initializing every struct makes tests longer without much benefit (spencerschrock)
    - testpackage # tests don't need their own package (spencerschrock)
  presets:
    - bugs
    - test
linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  exhaustive:
    # https://golangci-lint.run/usage/linters/#exhaustive
    default-signifies-exhaustive: true
  forbidigo:
    forbid:
      - p: "^fmt\\.Print.*$"
        msg: "Do not commit print statements. Output to stdout interferes with users who redirect JSON results to files."
  govet:
    enable:
      - fieldalignment
  godox:
    keywords:
      - BUG
      - FIXME
      - HACK
  gosec:
    excludes:
      # TODO investigate and fix separately
      - G115 # integer overflow conversion
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/ossf/scorecard)
  gocritic:
    disable-all: true
    enabled-checks:
      # Diagnostic
      - appendAssign
      - argOrder
      - badCall
      - badCond
      - caseOrder
      - codegenComment
      - commentedOutCode
      - deprecatedComment
      - dupArg
      - dupBranchBody
      - dupCase
      - dupSubExpr
      - exitAfterDefer
      - flagDeref
      - flagName
      - mapKey
      - nilValReturn
      - octalLiteral
      - offBy1
      - sloppyLen
      - sloppyTypeAssert
      - weakCond

      # Performance
      - appendCombine
      - hugeParam
      - rangeExprCopy
      - rangeValCopy

      # Style
      - assignOp
      - boolExprSimplify
      - captLocal
      - commentedOutImport
      - commentFormatting
      - defaultCaseOrder
      - docStub
      - elseif
      - emptyFallthrough
      - hexLiteral
      - ifElseChain
      - methodExprCall
      - newDeref
      - regexpMust
      - singleCaseSwitch
      - switchTrue
      - typeAssertChain
      - typeSwitchVar
      - underef
      - unlabelStmt
      - unlambda
      - unslice
      - valSwap
      - wrapperFunc

      # Opinionated
      - builtinShadow
      - importShadow
      - initClause
      - nestingReduce
      - paramTypeCombine
      - ptrToRefParam
      - typeUnparen
      - unnecessaryBlock
  nolintlint:
    # `//nolint` should mention specific linter such as `//nolint:my-linter`
    # Overly broad directives can hide unrelated issues
    require-specific: true
  wrapcheck:
    ignorePackageGlobs:
      - github.com/ossf/scorecard/v5/checks/fileparser
