project_name: scorecard
env:
  - GO111MODULE=on
  - CGO_ENABLED=1
before:
  hooks:
    - go mod download
builds:

- id: linux
  binary: scorecard-linux-{{ .Arch }}
  no_unique_dist_dir: true
  goos:
    - linux
  goarch:
    - amd64
    - arm64
    - 386
    - arm
  ldflags:
    - -s -w {{.Env.VERSION_LDFLAGS}} 

- id: darwin
  binary: scorecard-darwin-{{ .Arch }}
  no_unique_dist_dir: true
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w {{.Env.VERSION_LDFLAGS}} 

- id: windows
  binary: scorecard-windows-{{ .Arch }}
  no_unique_dist_dir: true
  goos:
    - windows
  goarch:
    - amd64
    - 386
    - arm64
    - arm
  ldflags:
    - -buildmode=exe
    - -s -w {{.Env.VERSION_LDFLAGS}} 

checksum:
  # Algorithm to be used.
  # Accepted options are sha256, sha512, sha1, crc32, md5, sha224 and sha384.
  # Default is sha256.
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha512

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}
changelog:
  use: github
  # Set it to true if you wish to skip the changelog generation.
  # This may result in an empty release notes on GitHub/GitLab/Gitea.
  skip: false
signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

release:
  footer: |
    ### Thanks for all contributors!
