version: 1
env:
  - GO111MODULE=on
  # https://stackoverflow.com/a/62821358/19407
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

goos: linux
goarch: amd64
binary: scorecard-{{ .Os }}-{{ .Arch }}
ldflags:
  - -s {{ .Env.VERSION_LDFLAGS }}