version: 1
env:
  - GO111MODULE=on
  # https://stackoverflow.com/a/62821358/19407
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

#TODO:
#mod_timestamp: '{{ .CommitTimestamp }}'
goos: linux
goarch: amd64
binary: binary-{{ .OS }}-{{ .Arch }}
ldflags:
  - '{{ .Env.VERSION_LDFLAGS }}'
