# Copyright 2023 OpenSSF Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
- id: 'Get Git history'
  name: 'gcr.io/cloud-builders/git'
  args: ['fetch', '--unshallow', '--tags', 'origin', '$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.',
    '-t', 'gcr.io/openssf/scorecard-attestor:latest',
    '-t', 'gcr.io/openssf/scorecard-attestor:$COMMIT_SHA',
    '-f', 'attestor/Dockerfile']
images: ['gcr.io/openssf/scorecard-attestor']
