apiVersion: v1
items:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"batch/v1beta1","kind":"CronJob","metadata":{"annotations":{},"name":"daily-score","namespace":"default"},"spec":{"jobTemplate":{"spec":{"template":{"spec":{"containers":[{"command":["/bin/sh","-c","./cron/cron.sh"],"env":[{"name":"GITHUB_AUTH_TOKEN","valueFrom":{"secretKeyRef":{"key":"token","name":"github"}}},{"name":"GCS_BUCKET","value":"ossf-scorecards"}],"image":"gcr.io/openssf/cron:latest","imagePullPolicy":"Always","name":"run-score"}],"restartPolicy":"OnFailure"}}}},"schedule":"0 8 * * *"}}
    creationTimestamp: "2020-11-11T17:47:07Z"
    managedFields:
    - apiVersion: batch/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:spec:
          f:concurrencyPolicy: {}
          f:failedJobsHistoryLimit: {}
          f:jobTemplate:
            f:spec:
              f:template:
                f:spec:
                  f:containers:
                    k:{"name":"run-score"}:
                      .: {}
                      f:command: {}
                      f:env:
                        .: {}
                        k:{"name":"GCS_BUCKET"}:
                          .: {}
                          f:name: {}
                          f:value: {}
                        k:{"name":"GITHUB_AUTH_TOKEN"}:
                          .: {}
                          f:name: {}
                          f:valueFrom:
                            .: {}
                            f:secretKeyRef:
                              .: {}
                              f:key: {}
                              f:name: {}
                      f:image: {}
                      f:imagePullPolicy: {}
                      f:name: {}
                      f:resources: {}
                      f:terminationMessagePath: {}
                      f:terminationMessagePolicy: {}
                  f:dnsPolicy: {}
                  f:restartPolicy: {}
                  f:schedulerName: {}
                  f:securityContext: {}
                  f:terminationGracePeriodSeconds: {}
          f:schedule: {}
          f:successfulJobsHistoryLimit: {}
      manager: kubectl
      operation: Update
      time: "2021-02-16T18:49:08Z"
    - apiVersion: batch/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:suspend: {}
      manager: GoogleCloudConsole
      operation: Update
      time: "2021-03-09T21:41:13Z"
    - apiVersion: batch/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:active: {}
          f:lastScheduleTime: {}
      manager: kube-controller-manager
      operation: Update
      time: "2021-03-10T00:00:03Z"
    name: daily-score
    namespace: default
    resourceVersion: "61300072"
    selfLink: /apis/batch/v1beta1/namespaces/default/cronjobs/daily-score
    uid: dbfc0fb0-a5c9-4694-8366-4616a5485683
  spec:
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 1
    jobTemplate:
      metadata:
        creationTimestamp: null
      spec:
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers:
            - command:
              - /bin/sh
              - -c
              - ./cron/cron.sh
              env:
              - name: GITHUB_AUTH_TOKEN
                valueFrom:
                  secretKeyRef:
                    key: token
                    name: github
              - name: GCS_BUCKET
                value: ossf-scorecards
              - name: BLOB_URL
                value: "gs://ossf-scorecards-cache"
              - name: USE_BLOB_CACHE
                value: true
              image: gcr.io/openssf/cron:latest
              imagePullPolicy: Always
              name: run-score
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
            dnsPolicy: ClusterFirst
            restartPolicy: OnFailure
            schedulerName: default-scheduler
            securityContext: {}
            terminationGracePeriodSeconds: 30
    schedule: 0 0 * * 0,3
    successfulJobsHistoryLimit: 3
    suspend: false
  status:
    active:
    - apiVersion: batch/v1
      kind: Job
      name: daily-score-1615334400
      namespace: default
      resourceVersion: "61227690"
      uid: a0894cd4-ae96-45df-9f4f-bf4072ee035c
    lastScheduleTime: "2021-03-10T00:00:00Z"
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
