// Copyright 2023 OpenSSF Scorecard Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
Scdiff is a tool to create and diff goldens when analyzing results.
These results can be from different points in time, or generated by differnet versions of Scorecard.

Intended usage:

1. Use scdiff generate on a list of repositories to produce the golden file.

2. Similarly, evaluate the same list using the proposed changed.

3. Run scdiff compare to compare the two files.

4. If changes are intentional and acceptable, run scdiff accept to merge the changes to the golden.
*/
package main

import "github.com/ossf/scorecard/v4/cmd/internal/scdiff/app"

func main() {
	app.Execute()
}
