# Copyright 2021 Security Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import json

import yaml

with open('checks.yaml') as f:
    checks = yaml.safe_load(f)

with open('checks.json', 'w') as f:
  f.write(json.dumps(checks))

with open('checks.md', 'w') as f:
  f.write("""
<!-- Do not edit this file manually! Edit checks.yaml instead. -->
# Check Documentation

This page contains information on how each check works and provide remediation
steps to fix the failure. All of these checks are basically "best-guesses"
currently, and operate on a set of heuristics.

They are all subject to change, and have room for improvement!
If you have ideas for things to add, or new ways to detect things,
please contribute!
""")

  for check, info in checks['checks'].items():
    f.write('## ' + check + '\n')
    f.write(info['description'] + '\n\n')
    f.write('**Remediation steps**:\n')
    for remediation in info['remediation']:
      f.write('- ' + remediation + '\n')
    f.write('\n')


