# Copyright 2021 Security Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

RUN go get github.com@some_tag
RUN go install github.com@some_tag
RUN ["go", "install", "github.com@tag"]
RUN ["go", "install"]

RUN go install github.com@some_tag
RUN go get github.com@some_tag
RUN go get github.com@1111111111ccccccccccaaaaaaaaaa9999999999
RUN go get github.com@1111111111ccccccccccaaaaaaaaaa9999999999
RUN ["go", "install", "-Y", "github.com@1111111111ccccccccccaaaaaaaaaa9999999999"]
RUN ["go", "get", "github.com@1111111111ccccccccccaaaaaaaaaa9999999999"]

RUN go mod download
RUN go build -a bla

RUN ["pip", "install", "-r", "requirements.txt"]
RUN ["pip3", "install", "-r", "requirements.txt"]
RUN ["/bin/pip", "install", "-r", "requirements.txt"]
RUN ["pip3", "install"]
RUN ["pip", "install"]
RUN ["/bin/pip", "install", "-U"]
RUN pip install
RUN pip3 install
RUN pip install -r any_file
RUN pip3 install -r bla-requirements.txt

RUN pip install somepkg
RUN pip3 install somepkg==1.2.3
RUN /bin/pip3 install -X -H somepkg

RUN python -m notpip -X bla

RUN python2.7 -m pip install -X -H somepkg \
    'some-ther==1.2.3' \
    'somebla<3.4.5'

RUN ["python", "-m", "pip", "install", "-X", "-H", "somepkg", \
    "'some-ther==1.2.3'", \
    "'somebla<3.4.5'"]

RUN ["python3", "-m", "pip", "install", "-X", "-H", "somepkg", \
    "'some-ther==1.2.3'", \
    "'somebla<3.4.5'"]

RUN python -m pip install bla1.whl 'some-pkg>1.2.3'
RUN python -m pip install "some-pkg>1.2.3" bla2.whl
RUN python -m pip install 'some-pkg>1.2.3' bla2.whl
RUN python -m pip install bla3.whl

RUN python -m pip install -r file
RUN python -m pip install 'some-pkg==1.2.3'
RUN python -m pip install 'some-pkg>1.2.3'