
# Copyright 2021 Security Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.7@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2

RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/exe9 . 
RUN exe9

RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/exe /tmp/file1 && /tmp/file1
RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/exe /tmp/file2 ; /tmp/file2

RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/exe . && exe
RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/exe /path/to/ && /path/to/exe
RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/exe2 /path/to/
RUN /path/to/exe2

RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/script9 . 
RUN bash script9

RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/script /tmp/file1 && bash /tmp/file1
RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/script /tmp/file2 ; bash /tmp/file2

RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/script . && bash script
RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/script /path/to/ && bash /path/to/script
RUN aws s3api get-object --bucket DOC-EXAMPLE-BUCKET1 --key dir/script2 /path/to/
RUN bash /path/to/script2

RUN ["aws", "s3api", "get-object", "--bucket", "DOC-EXAMPLE-BUCKET1", "--key", "dir/exe10", "."]
RUN ["exe10"]

FROM scratch
FROM python@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2