#!/bin/bash
# Copyright 2021 Security Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

go get github.com@some_tag
go install github.com@some_tag
go install

/bin/go install github.com@some_tag
go get github.com@some_tag
go get github.com@1111111111ccccccccccaaaaaaaaaa9999999999
go get github.com@1111111111ccccccccccaaaaaaaaaa9999999999
go install -Y github.com@1111111111ccccccccccaaaaaaaaaa9999999999
go get github.com@1111111111ccccccccccaaaaaaaaaa9999999999

go mod download
go build -a bla

pip install -r requirements.txt
/bin/pip install -r requirements.txt
pip3 install
/bin/pip install -U
pip install
pip install -r any_file
pip3 install -r bla-requirements.txt

pip install somepkg
pip3 install somepkg==1.2.3
/bin/pip3 install -X -H somepkg

python -m notpip -X bla

python -m pip install -r file
python -m pip install 'some-pkg==1.2.3'
python -m pip install 'some-pkg>1.2.3'

python -m pip install bla.whl 'some-pkg>1.2.3'
python -m pip install 'some-pkg>1.2.3' bla.whl
python -m pip install "some-pkg>1.2.3" bla.whl
python -m pip install bla.whl
python -m pip install bla.whl "some-pkg>1.2.3"

python2.7 -m pip install -X -H somepkg \
    'some-ther==1.2.3' \
    'somebla<3.4.5'

python -m pip install -X -H somepkg \
    'some-ther==1.2.3' \
    'somebla<3.4.5'

python3 -m pip install -X -H somepkg \
    'some-ther==1.2.3' \
    'somebla<3.4.5'
    