# Copyright 2021 OpenSSF Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Note: taken from https://github.com/pushiqiang/utils/blob/master/docker/Dockerfile_template
# Add tab
    FROM python:3.7

# 如果在中国，apt使用163源, ifconfig.co/json, http://ip-api.com 
#RUN curl -s ifconfig.co/json | grep "China" > /dev/null && \
#    curl -s http://mirrors.163.com/.help/sources.list.jessie > /etc/apt/sources.list || true

# 安装开发所需要的一些工具，同时方便在服务器上进行调试
#RUN apt-get update;\
#    apt-get install -y vim;\
#    true

#RUN mkdir /opt/somedir

#ENV PROJECT_NAME='test'
#ENV PYTHONPATH="${PYTHONPATH}:/opt/somedir"

#COPY src/ /opt/somedir
#WORKDIR /opt/somedir

RUN echo hello && \
	curl bla | bash

# 如果在中国，pip使用豆瓣源
#RUN curl -s ifconfig.co/json | grep "China" > /dev/null && \
#    pip install -r requirements.txt -i https://pypi.doubanio.com/simple --trusted-host pypi.doubanio.com || \
RUN bla && \
	pip install -r requirements.txt

RUN pip install --no-deps --editable .
RUN pip install --no-deps -e .
RUN pip install --no-deps -e hg+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e svn+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e bzr+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+https://github.com/username/repo.git
RUN pip install --no-deps -e git+https://github.com/username/repo.git#egg=package
RUN pip install --no-deps -e git+https://github.com/username/repo.git@v1.0
RUN pip install --no-deps -e git+https://github.com/username/repo.git@v1.0#egg=package
RUN pip install --no-deps -e git+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567
RUN pip install --no-deps -e git+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+https://github.com/username/repo@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+http://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+ssh://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+git://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install -e git+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package

RUN python -m pip install --no-deps -e git+https://github.com/username/repo.git
RUN python -m pip install --no-deps -e git+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package