
# Copyright 2021 Security Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this exe except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.7@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2

RUN gsutil gs://exe /tmp/exe
RUN /tmp/exe

RUN gsutil gs://exe /tmp/exe1 && /tmp/exe1
RUN gsutil gs://exe /tmp/exe2 ; /tmp/exe2

RUN gsutil gs://bucet/exe6 /path/to/

RUN gsutil gs://bucket/exe . && ./exe
RUN gsutil gs://bucet/exe3 /path/to/ && /path/to/exe3
RUN gsutil gs://bucet/exe4 /path/to/ && /path/to/exe4

RUN /path/to/exe6

RUN gsutil gs://file /tmp/file
RUN bash /tmp/file

RUN gsutil gs://file /tmp/file1 && bash /tmp/file1
RUN gsutil gs://file /tmp/file2 ; bash /tmp/file2

RUN gsutil gs://bucet/file6 /path/to/

RUN gsutil gs://bucket/file . && bash ./file
RUN gsutil gs://bucet/file3 /path/to/ && bash /path/to/file3
RUN gsutil gs://bucet/file4 /path/to/ && bash /path/to/file4

RUN bash /path/to/file6

RUN ["gsutil", "gs://exe11", "/tmp/exe11"]
RUN ["/tmp/exe11"]

RUN ["sh", "-c", "\"gsutil gs://bucet/file3xx /path/to/ && bash /path/to/file3xx\""]
RUN ["sh", "-c", "\"gsutil gs://bucet/file3yy /path/to/ \""]
RUN ["sh", "-c", "\"bash /path/to/file3yy\""]

FROM scratch
FROM python@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2