# Copyright 2021 OpenSSF Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

RUN go get github.com/org/name@some_tag
RUN go install github.com/org/name@some_tag
RUN ["go", "install", "github.com/org/name@tag"]
RUN ["go", "install"]

RUN go install github.com/org/name@some_tag
RUN go get github.com/org/name@some_tag
RUN go get github.com/org/name@1111111111ccccccccccaaaaaaaaaa9999999999
RUN go get github.com/org/name@1111111111ccccccccccaaaaaaaaaa9999999999
RUN ["go", "install", "-Y", "github.com/org/name@1111111111ccccccccccaaaaaaaaaa9999999999"]
RUN ["go", "get", "github.com/org/name@1111111111ccccccccccaaaaaaaaaa9999999999"]
RUN ["go", "get", "somerepo.com/org/name@v1.2.3"]
RUN ["go", "get", "somerepo.com/org/name@v1.2.3-semver"]
RUN ["go", "get", "somerepo.com/org/name@v1.2.3-semver+great"]
RUN ["go", "get", "-insecure", "somerepo.com/org/name@v1.2.3"]
RUN ["go", "get", "-insecure", "somerepo.com/org/name@v1.2.3-semver"]
RUN ["go", "get", "-insecure", "somerepo.com/org/name@v1.2.3-semver+great"]
RUN ["go", "get", "somerepo.com/org/name@v1"]
RUN ["go", "get", "somerepo.com/org/name@v1.2"]
RUN ["go", "get", "somerepo.com/org/name@none"]
RUN ["go", "get", "somerepo.com/org/name@latest"]
RUN ["go", "get", "somerepo.com/org/name@patch"]
RUN ["go", "get", "somerepo.com/org/name@upgrade"]

RUN go install /some/local/path
RUN go mod download
RUN go build -a bla

RUN ["pip", "install", "-r", "requirements.txt"]
RUN ["pip3", "install", "-r", "requirements.txt"]
RUN ["/bin/pip", "install", "-r", "requirements.txt"]
RUN ["pip3", "install"]
RUN ["pip", "install"]
RUN ["/bin/pip", "install", "-U"]
RUN pip install
RUN pip3 install
RUN pip install -r any_file
RUN pip3 install -r bla-requirements.txt
RUN ["pip", "install", "-r", "requirements.txt", "--require-hashes"]
RUN ["pip3", "install", "-r", "requirements.txt", "--require-hashes"]
RUN ["/bin/pip", "install", "--upgrade", "-r", "requirements.txt"]
RUN ["/bin/pip", "install", "--upgrade"]
RUN pip3 install -r bla-requirements.txt --require-hashes
RUN pip3 install --require-hashes -r bla-requirements.txt

RUN pip install somepkg
RUN pip3 install somepkg==1.2.3
RUN /bin/pip3 install -X -H somepkg

RUN pip install --no-deps --editable .
RUN pip install --no-deps -e .
RUN pip install --no-deps -e hg+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e svn+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e bzr+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+https://github.com/username/repo.git
RUN pip install --no-deps -e git+https://github.com/username/repo.git#egg=package
RUN pip install --no-deps -e git+https://github.com/username/repo.git@v1.0
RUN pip install --no-deps -e git+https://github.com/username/repo.git@v1.0#egg=package
RUN pip install --no-deps -e git+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567
RUN pip install --no-deps -e git+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+https://github.com/username/repo@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+http://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+ssh://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git+git://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e git://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install -e git+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package
RUN pip install --no-deps -e . git+https://github.com/username/repo.git
RUN pip install --no-deps -e . git+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package

RUN python -m notpip -X bla

RUN python2.7 -m pip install -X -H somepkg \
    'some-ther==1.2.3' \
    'somebla<3.4.5'

RUN ["python", "-m", "pip", "install", "-X", "-H", "somepkg", \
    "'some-ther==1.2.3'", \
    "'somebla<3.4.5'"]

RUN ["python3", "-m", "pip", "install", "-X", "-H", "somepkg", \
    "'some-ther==1.2.3'", \
    "'somebla<3.4.5'"]

RUN python -m pip install bla1.whl 'some-pkg>1.2.3'
RUN python -m pip install "some-pkg>1.2.3" bla2.whl
RUN python -m pip install 'some-pkg>1.2.3' bla2.whl
RUN python -m pip install bla3.whl

RUN python -m pip install -r file
RUN python -m pip install 'some-pkg==1.2.3'
RUN python -m pip install 'some-pkg>1.2.3'

RUN python -m pip install --no-deps -e git+https://github.com/username/repo.git
RUN python -m pip install --no-deps -e git+https://github.com/username/repo.git@0123456789abcdef0123456789abcdef01234567#egg=package

RUN npm install typescript
RUN npm install -g typescript
RUN npm i typescript
RUN npm i -g typescript
RUN npm install
RUN npm install -g
RUN npm i
RUN npm ci
RUN npm install-test
RUN npm install-ci-test

RUN choco install 'some-package'
RUN choco install 'some-other-package'
RUN choco install --requirechecksum 'some-package'
RUN choco install --requirechecksums 'some-package'
RUN choco install --require-checksums 'some-package'


RUN nuget install some-package
RUN nuget restore
RUN nuget install some-package -Version 1.2.3
RUN nuget install packages.config
RUN dotnet add package some-package
RUN dotnet add SomeProject package some-package
RUN dotnet build
RUN dotnet add package some-package -v 1.2.3
RUN dotnet add package some-package --version 1.2.3
RUN dotnet add SomeProject package some-package --version 1.2.3