
# Copyright 2021 Security Scorecard Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this exe except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.7@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2

RUN wget http://exe-with-sudo -O /tmp/exe
RUN /tmp/exe

RUN wget http://exe-with-sudo -O /tmp/exe1 && /tmp/exe1
RUN wget http://exe-with-sudo -O /tmp/exe2 ; /tmp/exe2

RUN wget http://domain.com/exe && ./exe

RUN wget http://file-with-sudo -O /tmp/file
RUN bash /tmp/file

RUN wget http://file-with-sudo -O /tmp/file1 && bash /tmp/file1
RUN wget http://file-with-sudo -O /tmp/file2 ; bash /tmp/file2

RUN wget http://domain.com/file && bash ./file
RUN ["/bin/wget", "http://domain.com/file111", "&&", "bash", "./file111"]

RUN ["/bin/sh", "-c", "\"/bin/curl http://domain.com/file1112 | bash ./file1112\""]

FROM scratch
FROM python@sha256:45b23dee08af5e43a7fea6c4cf9c25ccf269ee113168c19722f87876677c5cb2