name: test secrets
on: 
  - workflow_dispatch
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get status
        run: |
          echo "GH_AUTH_TOKEN:"
          export GH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}
          gh auth login || echo "failed login"
          gh auth status || echo "failed status"
          
          echo "PERSONAL_ACCESS_TOKEN:"
          export GH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          gh auth login || echo "failed login"
          gh auth status || echo "failed status"
          
          echo "SCORECARD_TOKEN:"
          export GH_TOKEN=${{ secrets.SCORECARD_TOKEN }}
          gh auth login || echo "failed login"
          gh auth status || echo "failed status"

      - name: create comment
        run: |
          ISSUE_NUMBER=2657
          export GH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            /repos/$GITHUB_REPOSITORY/issues/$ISSUE_NUMBER/comments \
            -f body='test'
      - name: addition in PR
        run: |
          echo "hello"
