name: test secrets
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "GH_AUTH_TOKEN:"
          export GH_TOKEN=${{ secrets.GH_AUTH_TOKEN }}
          gh auth login || echo "failed login"
          gh auth status || echo "failed status"
          
          echo "PERSONAL_ACCESS_TOKEN:"
          export GH_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }}
          gh auth login || echo "failed login"
          gh auth status || echo "failed status"
          
          echo "SCORECARD_TOKEN:"
          export GH_TOKEN=${{ secrets.SCORECARD_TOKEN }}
          gh auth login || echo "failed login"
          gh auth status || echo "failed status"
